### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by erikkjellgren** [Janne252/LiveSplit.CoH2CampaignAutoSplit#1]
The link in the description pointing at the .lss file does not work.

https://github.com/Janne252/LiveSplit.CoH2CampaignAutoSplit/blob/d35272f175a82e4e8ebc3bdfadad9ce39786fadc/templates/coh2-sp-campaign.lss

This link leads nowhere.

**Comment by Janne252** [comment]
Thanks for the report. The `.lss` file is now available.
